apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-pvc-backup
  namespace: postgresql-integration
  labels:
    app.kubernetes.io/name: postgresql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: csi-rbd-sc
